export class FakeDataBtnState {
	constructor(
		public all: boolean = false,
		public hardcoded: boolean = false,
		public clearAll: boolean = false,
		public invite1: boolean = false,
		public invite2: boolean = false,
		public invite3: boolean = false,
		public invite4: boolean = false,
		public user: boolean = false,
		public users100: boolean = false,
		public carrier1: boolean = false,
		public carrier2: boolean = false,
		public carrier3: boolean = false,
		public carriers100: boolean = false,
		public product1: boolean = false,
		public product2: boolean = false,
		public product3: boolean = false,
		public product4: boolean = false,
		public product5: boolean = false,
		public product6: boolean = false,
		public warehouse1: boolean = false,
		public warehouse2: boolean = false,
		public warehouse3: boolean = false,
		public warehouse100: boolean = false,
		public warehouseProduct1: boolean = false,
		public warehouseProduct2: boolean = false,
		public warehouseProduct3: boolean = false,
		public warehouseGeoLocation: boolean = false,
		public createOrder1: boolean = false,
		public createOrder2: boolean = false,
		public create1000Orders: boolean = false,
		public confirmOrder1: boolean = false,
		public confirmOrder2: boolean = false
	) {}
}
